name: Build and Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'adopt'

      - name: Generate Gradle wrapper
        run: gradle wrapper --gradle-version 9.2.1
        shell: bash

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build
        shell: bash

      - name: Create executable
        run: ./gradlew createExe
        shell: bash

      - name: Create ZIP archive
        run: ./gradlew createZip
        shell: bash

      - name: Upload application image as asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/dist/VerLink/VerLink.exe
          asset_name: VerLink.exe
          asset_content_type: application/vnd.microsoft.portable-executable

      - name: Upload ZIP archive as asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/dist/verlink-0.0.0-win.zip
          asset_name: verlink-0.0.0-win.zip
          asset_content_type: application/zip